name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.15
          cache: "npm"

      - name: Build
        run: |
          npm install bower -g
          npm install
          composer install
          npm run build

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: widgetkit-for-elementor
